### ISSUE TITLE
running of gc_runfcst_hera.sh  gave error : ModuleNotFoundError: No module named 'botocore' 

### ISSUE THREAD

**Issue by TingLei-NOAA** [NOAA-EMC/graphcast#43]
Dear  GFSGraphcast experts,
It seems there are some problems with  boto module:
submitting gc_runfcst_hera.sh gave error message: 
```
Traceback (most recent call last):
  File "/scratch2/NCEPDEV/fv3-cam/Ting.Lei/dr-emc-graphcast/graphcast/NCEP/run_graphcast.py", line 20, in <module>
    import boto3
  File "/scratch1/NCEPDEV/nems/AIML/miniconda3/envs/mlwp/lib/python3.10/site-packages/boto3/__init__.py", line 16, in <module>
    from boto3.compat import _warn_deprecated_python
  File "/scratch1/NCEPDEV/nems/AIML/miniconda3/envs/mlwp/lib/python3.10/site-packages/boto3/compat.py", line 19, in <module>
    from boto3.exceptions import PythonDeprecationWarning
  File "/scratch1/NCEPDEV/nems/AIML/miniconda3/envs/mlwp/lib/python3.10/site-packages/boto3/exceptions.py", line 15, in <module>
    import botocore.exceptions
ModuleNotFoundError: No module named 'botocore'
~
```
Thanks

**Comment by kiki840306** [comment]
u should use conda install botocore

**Comment by SadeghTabas-NOAA** [comment]
@TingLei-NOAA This issue comes from the version of the botocore you are using, please use the latest version and it will resolve the issue. Thanks

**Comment by SadeghTabas-NOAA** [comment]
I close this issue, Thanks
