### ISSUE TITLE
Error: cube_slice.coord('latitude').coord_system = iris.coord_systems.GeogCS(4326)

### ISSUE THREAD

**Issue by kiki840306** [NOAA-EMC/graphcast#52]
when i run the model fellow the introduction on the web, i get this errors from run the main model. we tested the cube_slice.coord('latitude').coord_system = iris.coord_systems.GeogCS(4326), There is no problem with the test on the right side of the equal sign. wo guess the problem would be in the left. can u give some information.

Forecast start time is 2024-08-07 06:00:00
Processing for time 2024-08-07 06:00:00
/home/graphcast/mode/output/forecasts_13_levels/graphcastgfs.t06z.pgrb2.0p25.f000
Traceback (most recent call last):
  File "/home/graphcast/mode/NCEP/run_graphcast.py", line 269, in &lt;module&gt;
    runner.get_predictions()
  File "/home/graphcast/mode/NCEP/run_graphcast.py", line 180, in get_predictions
    self.save_grib2(forecasts)
  File "/home/graphcast/mode/NCEP/run_graphcast.py", line 194, in save_grib2
    converter.save_grib2(self.dates, ds, self.output_dir)
  File "/home/graphcast/mode/NCEP/utils/nc2grib.py", line 120, in save_grib2
    cube_slice.coord('latitude').coord_system = iris.coord_systems.GeogCS(4326)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/graphcast/anaconda3/envs/Swj/lib/python3.12/site-packages/iris/cube.py", line 2305, in coord
    raise iris.exceptions.CoordinateNotFoundError(emsg)
iris.exceptions.CoordinateNotFoundError: "Expected to find exactly 1 'latitude' coordinate, but found none."

**Comment by SadeghTabas-NOAA** [comment]
Please try to install the dependencies on a clean environment as follows:
https://github.com/NOAA-EMC/graphcast/blob/main/NCEP/Readme.md

**Comment by SadeghTabas-NOAA** [comment]
I close this issue, Thanks
